### ISSUE TITLE
BlogProperties.kt code is referenced before it is created in tutorial

### ISSUE THREAD

**Issue by norricorp** [spring-guides/tut-spring-boot-kotlin#34]
In the tutorial, HtmlController.kt uses properties.title but properties is not defined. 
Tutorial updates HtmlController.kt as

```
@Controller
class HtmlController(private val repository: ArticleRepository) {
….
}
```
when should be
```
@Controller
class HtmlController(private val repository: ArticleRepository,
					            private val properties: BlogProperties) {
….
}
```
except that BlogProperties is mentioned later in the tutorial. But before this tutorial says to run code to see the new screens.

Adding BlogProperties.kt early with the above does allow it to compile  But for the tests to run, BlogApplication.kt neds to be updated (as in explained in the tutorial much later). Though this still causes a test to fail.

**Comment by sdeleuze** [comment]
I guess it has been fixed by https://github.com/spring-guides/tut-spring-boot-kotlin/pull/32, please reopen if that's not the case.

**Comment by norricorp** [comment]
Looking thru' the current version of the tutorial, this has not been fixed. Setting up configuration properties (ie BlogProperties.kt ) is still after the instruction to run the app when you are have referenced the contents of the non existent BlogProperties.kt.
Also the comment above of "I guess it has been fixed by …". Shouldn't you have tested this? It is your work.

**Comment by sdeleuze** [comment]
> Setting up configuration properties (ie BlogProperties.kt ) is still after the instruction to run the app when you are have referenced the contents of the non existent BlogProperties.kt.

It seems to me #32 has updated the tuto to not reference anymore `properties.title` so `BlogProperties` is not required anymore before the "Configuration properties" part. I may of course have missed something, could you please be more specific?

> Also the comment above of "I guess it has been fixed by …". Shouldn't you have tested this? It is your work.

Please stay kind
