### ISSUE TITLE
MediaType.APPLICATION_JSON_UTF8 is Deprecated

### ISSUE THREAD

**Issue by Nt-gm79sp** [spring-guides/tut-spring-boot-kotlin#41]
In `HttpControllersTests.kt` , I got a warning that `APPLICATION_JSON_UTF8` is [deprecated](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/http/MediaType.html#APPLICATION_JSON_UTF8).
Would you please fix this issue? Thanks!

AND:
Thanks for your excellent tutorial!

**Comment by sdeleuze** [comment]
There is no more `APPLICATION_JSON_UTF8` in https://github.com/spring-guides/tut-spring-boot-kotlin/blob/master/src/test/kotlin/com/example/blog/HttpControllersTests.kt, I already did the update, I guess you are using an outdated fork or something like that.

Thanks, glad you liked it.
