### ISSUE TITLE
Gradle sync fails

### ISSUE THREAD

**Issue by hrsma2i** [spring-guides/tut-spring-boot-kotlin#44]
I'm a beginner in Java, Kotlin. I'm trying to build a web backend using Kotlin, SpringBoot and IntelliJ.

Gradle sync fails. The following error occurs.

<img width="911" alt="スクリーンショット 2020-05-10 17 52 08" src="https://user-images.githubusercontent.com/28626381/81495162-2ee4c000-92e9-11ea-922e-ada1f92409c3.png">
<img width="713" alt="スクリーンショット 2020-05-10 17 52 17" src="https://user-images.githubusercontent.com/28626381/81495163-30ae8380-92e9-11ea-888b-333f1ab820f0.png">

I also tried to remove `~/.gradle` and sync it again, but it still fails.

How can I get Gradle sync to succeed?

**Environments**

- IntelliJ IDEA 2018.1.7 (Community Edition)
- Build #IC-181.5540.23, built on November 12, 2018
- JRE: 1.8.0_152-release-1136-b43 x86_64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- macOS 10.14.6

**Comment by sdeleuze** [comment]
I would suggest to upgrade your IDEA version.
I can't reproduce on mine (2020.1).
