### ISSUE TITLE
`freeCompilerArgs` should use `+=` operator

### ISSUE THREAD

**Issue by TheBestPessimist** [spring-guides/tut-spring-boot-kotlin#53]
Please see: https://youtrack.jetbrains.com/issue/KT-41985

**Comment by sdeleuze** [comment]
Good catch!

**Comment by sdeleuze** [comment]
Is there is a concrete serious impact identified?
Otherwise I would be tempted to wait to see how this is tackled in Kotlin 1.6.

**Comment by sdeleuze** [comment]
I asked in https://youtrack.jetbrains.com/issue/KT-41985#focus=Comments-27-4967616.0-0.

**Comment by sdeleuze** [comment]
Fixed and I created the related https://github.com/spring-io/initializr/issues/1368 issue for start.spring.io.
