### ISSUE TITLE
Question: More details to note - why don't use immutable data classes

### ISSUE THREAD

**Issue by jwausle** [spring-guides/tut-spring-boot-kotlin#56]
I found Your note [here](https://github.com/spring-guides/tut-spring-boot-kotlin#persistence-with-jpa) ...
 
> Note: Here we don’t use data classes with val properties because JPA is not designed to work with immutable classes or the methods generated automatically by data classes.

I use `data class` with `val` attributes with JPA annotations and `JpaRepository` and it seems to work (since a while).

- DB: postgres 11
- Spring: 2.3.4
- Kotlin: 1.5.10
- Java: 11

Q: Could You give more details to Your note?
Q2: Which pitfalls/limitations exist with immutable data classes?
Q3: [This](https://www.jpa-buddy.com/blog/best-practices-and-common-pitfalls/) blog post address the same question. At the end with another conclusion. Who is wrong?

**Comment by sdeleuze** [comment]
https://github.com/sdeleuze/spring-boot-kotlin-demo is an old personal sample, this one is the reference. The [blog post linked](https://www.jpa-buddy.com/blog/best-practices-and-common-pitfalls/) explains why immutable data classes are not a good fit with JPA:
> To combat this issue, always override equals() and hashCode() when using data classes for entities.

> This is absolutely safe to use. However, it almost defeats the purpose of using data classes, as it makes decomposition useless and only uses one field in toString(). A plain old class might be a better option for entities.

So it is possible to use data classes with a lot of care but JPA is not really designed to work with them, hence the choice to use regular mutable classes in this project.
