### ISSUE TITLE
Fix H2 database support with Spring Boot 2.7+

### ISSUE THREAD

**Issue by scottfrederick** [spring-guides/tut-spring-boot-kotlin#60]
The entity named `User` causes problems with newer versions of the H2 database, where `user` is a reserved word so it can't be used as a table name. See https://github.com/spring-projects/spring-boot/issues/31771 for more details.

**Comment by sdeleuze** [comment]
I think I prefer to update Spring Boot configuration as suggested [here](https://github.com/spring-projects/spring-boot/issues/31771#issuecomment-1186232118).
