### ISSUE TITLE
Enable Annotation Processor not work

### ISSUE THREAD

**Issue by Space125** [spring-guides/tut-spring-boot-kotlin#63]
Greetings, I copied the project and enabled annotation processors in the settings, but I get an error "Spring Boot Configuration Annotation Processor not configured". Please tell me how to set up annotation processors correctly?

**Comment by sdeleuze** [comment]
Gradle or Maven? What IDEA and Kotlin plugin versions?

**Comment by Space125** [comment]
Gradle
IntelliJ IDEA 2022.3.3 (Ultimate Edition)
Kotlin plugin = 1.8.20

**Comment by sdeleuze** [comment]
I tried and it worked after doing Menu build -> Build project after enable annotation processors with IDEA 2023.1.2. Can you check after doing a full rebuild of the project?

**Comment by sdeleuze** [comment]
Closing due to lack of feedback.
