### ISSUE TITLE
[issue] error: unresolved reference: springframework on compilaton

### ISSUE THREAD

**Issue by Gelassen** [spring-guides/tut-spring-boot-kotlin#66]
### Steps to reproduce
1. Go through official guide https://spring.io/guides/tutorials/spring-boot-kotlin
2. At the end of a chapter "Writing your first Kotlin controller" run the project

### Observed behaviour
Console shows this errors:
```
BlogApplication.kt:3:12: error: unresolved reference: springframework
import org.springframework.boot.autoconfigure.SpringBootApplication
           ^
BlogApplication.kt:4:12: error: unresolved reference: springframework
import org.springframework.boot.context.properties.EnableConfigurationProperties
           ^
BlogApplication.kt:5:12: error: unresolved reference: springframework
import org.springframework.boot.runApplication
           ^
BlogApplication.kt:7:2: error: unresolved reference: SpringBootApplication
@SpringBootApplication
 ^
BlogApplication.kt:8:2: error: unresolved reference: EnableConfigurationProperties
@EnableConfigurationProperties(BlogProperties::class)
 ^
BlogApplication.kt:8:32: error: unresolved reference: BlogProperties
@EnableConfigurationProperties(BlogProperties::class)
                               ^
BlogApplication.kt:12:2: error: unresolved reference: runApplication
	runApplication<BlogApplication>(*args)
 ^

[Done] exited with code=1 in 2.777 seconds
```

### Expected behaviour
go to http://localhost:8080/, you should see a sober web page with a "Blog" headline.

### Environment
VSCode, Ubuntu 22.04, kotlin 1.9 (installed over snap), all required extensions enumerated in the guide

Obviously, it is an issue with my environment, the issue is reproduced even with code from this master branch.

**Comment by sdeleuze** [comment]
> Obviously, it is an issue with my environment, the issue is reproduced even with code from this master branch.
Indeed, so I will close this issue as there is no actionable item on our side.

FWIW, I have upgraded the versions to the latests on the `main` branch, everything is fine either with Gradle or Maven.
