### ISSUE TITLE
JAXB dependency is missing

### ISSUE THREAD

**Issue by maik** [spring-guides/tut-spring-boot-kotlin#7]
I tried to tun the project using Oracle JDK 10.0.1, but it failed, because JAXB was missing.

Adding
compile 'javax.xml.bind:jaxb-api:2.3.0' 
to the Gradle dependencies solved the problem.

**Comment by gregturn** [comment]
Adding Java 10 support is something we want to tackle consistently across all guides and tutorials.

**Comment by maik** [comment]
Ah, I see.

Apart from that everything worked fine, BTW.
